# Generated by Django 5.0.1 on 2024-03-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_model_name', models.CharField(max_length=100)),
                ('feature_names', models.CharField(max_length=800)),
            ],
        ),
    ]
