# Generated by Django 5.0.1 on 2024-03-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_data',
            name='label_encoder_model_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
